<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import StoryStudioDialog from '@/components/admin/story-studio/StoryStudioDialog.vue'
import StoryStudioState from '@/components/admin/story-studio/StoryStudioState.vue'
import StoryValidationSummary from '@/components/admin/story-studio/StoryValidationSummary.vue'
import { adminGetSourceVersion, adminGetStory, adminUpsertSource, getAdminValidationIssues, type AdminValidationIssue } from '@/lib/api'
import { importWouldReplaceSubstantialMarkdown, normaliseSourceForm, sourceFormFingerprint, sourceFormFromStory, sourceFormFromVersion, type StorySourceForm } from '@/lib/story-studio-form'
import { projectStoryStudioError, type StoryStudioError } from '@/lib/story-studio-navigation'

const emit=defineEmits<{ 'studio-dirty':[dirty:boolean] }>();const sourceProvenance=ref<import("@/lib/api").AdminSourceProvenance|null>(null); const route=useRoute(); const router=useRouter(); const form=ref<StorySourceForm>({title:'',author:'',language:'en-GB',rightsLabel:'',rights:{},sourceUrl:'',sourceText:''}); const baselineFingerprint=ref(''); const loading=ref(true); const loaded=ref(false); const loadError=ref<StoryStudioError|null>(null); const actionError=ref<StoryStudioError|null>(null); const validationIssues=ref<AdminValidationIssue[]>([]); const saving=ref(false); const sourceFilename=ref<string|null>(null); const pendingImport=ref<{filename:string;text:string}|null>(null); const importDialogOpen=ref(false); let generation=0; let controller:AbortController|null=null; let instanceAlive=true
const slug=computed(()=>String(route.params.slug??'')); const fingerprint=computed(()=>sourceFormFingerprint(form.value)); const dirty=computed(()=>loaded.value&&fingerprint.value!==baselineFingerprint.value); const issuesByField=computed<Record<string,string[]>>(()=>{const grouped:Record<string,string[]>={};for(const issue of validationIssues.value){grouped[issue.field]??=[];grouped[issue.field].push(issue.message)}return grouped})
watch(dirty,(value)=>emit('studio-dirty',value),{immediate:true})
async function moveToSignIn(){await router.replace({path:'/account/login',query:{next:route.path}})}
async function loadSource(){sourceProvenance.value=null;controller?.abort();controller=new AbortController();const activeGeneration=++generation;loading.value=true;loaded.value=false;loadError.value=null;actionError.value=null;validationIssues.value=[];emit('studio-dirty',false);try{const story=await adminGetStory(slug.value,controller.signal);if(activeGeneration!==generation||controller.signal.aborted)return;if(story.source.status==='repair_required'){loadError.value={kind:'repair',title:'Canonical source needs attention',message:'The stored canonical source cannot be opened safely. Reading editions remain independent.',retryable:false};return}let loadedForm=sourceFormFromStory(story);if(story.source.status==='ready'&&story.source.currentVersion){const source=await adminGetSourceVersion(story.slug,story.source.currentVersion.versionId,controller.signal);if(activeGeneration!==generation||controller.signal.aborted)return;loadedForm=sourceFormFromVersion(source);sourceProvenance.value=source.provenance??null}form.value=loadedForm;baselineFingerprint.value=sourceFormFingerprint(loadedForm);sourceFilename.value=null;loaded.value=true}catch(caught){if(controller.signal.aborted||activeGeneration!==generation)return;const projected=projectStoryStudioError(caught);loadError.value=projected;if(projected.kind==='session')await moveToSignIn()}finally{if(activeGeneration===generation)loading.value=false}}
function update<K extends keyof StorySourceForm>(key:K,value:StorySourceForm[K]){form.value={...form.value,[key]:value}}
function focusIssue(field:string){const ids:Record<string,string>={title:'source-title',author:'source-author',language:'source-language',rights:'source-rights',sourceUrl:'source-url',sourceText:'source-text'};document.getElementById(ids[field]??'source-text')?.focus()}
async function saveSource(){if(saving.value)return;saving.value=true;actionError.value=null;validationIssues.value=[];try{const result=await adminUpsertSource(slug.value,normaliseSourceForm(form.value));if(!instanceAlive)return;baselineFingerprint.value=fingerprint.value;emit('studio-dirty',false);await router.replace({name:'admin-story-detail',params:{slug:result.slug},query:{sourceSaved:result.outcome,sourceVersion:String(result.version)}})}catch(caught){if(!instanceAlive)return;validationIssues.value=getAdminValidationIssues(caught)??[];const projected=projectStoryStudioError(caught);actionError.value=projected;if(projected.kind==='session')await moveToSignIn();if(validationIssues.value.length){await nextTick();document.querySelector<HTMLElement>('.validation-summary')?.focus()}}finally{if(instanceAlive)saving.value=false}}
function applySourceImport(value:{filename:string;text:string}){update('sourceText',value.text);sourceFilename.value=value.filename;pendingImport.value=null;importDialogOpen.value=false}
async function importSource(file:File){const value={filename:file.name,text:await file.text()};if(!value.text.trim())return;if(importWouldReplaceSubstantialMarkdown(form.value.sourceText,value.text)){pendingImport.value=value;importDialogOpen.value=true;return}applySourceImport(value)}
function chooseSourceFile(){document.getElementById('source-file')?.click()}
function sourceFileChosen(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];input.value='';if(file)void importSource(file)}
watch(()=>route.fullPath,()=>void loadSource(),{immediate:true});onBeforeUnmount(()=>{instanceAlive=false;generation+=1;controller?.abort();emit('studio-dirty',false)})
</script>
<template>
  <div>
    <StoryStudioState v-if="loading && !loaded" kind="loading" title="Opening canonical source" message="Loading the current immutable source revision." />
    <StoryStudioState v-else-if="loadError" :kind="loadError.kind === 'repair' ? 'repair' : loadError.kind === 'forbidden' ? 'forbidden' : 'error'" :title="loadError.title" :message="loadError.message" :action-label="loadError.retryable ? 'Try again' : 'Return to story'" @action="loadError.retryable ? loadSource() : router.push(`/admin/stories/${encodeURIComponent(slug)}`)" />
    <template v-else-if="loaded">
      <header class="studio-page-heading source-heading"><div><p class="studio-page-heading__eyebrow">Canonical original</p><h1>Edit source material</h1><p class="studio-page-heading__summary">Source revisions are independent from all five reading editions. Saving never publishes or changes Reader.</p></div><button type="button" class="studio-button studio-button--primary" :disabled="saving" @click="saveSource">{{ saving ? 'Saving…' : 'Save source revision' }}</button></header>
      <p v-if="dirty" class="source-dirty">Unsaved changes</p><section v-if="sourceProvenance" class="studio-panel source-provenance"><h2>Source provenance</h2><p>Project Gutenberg #{{ sourceProvenance.externalId }} · Imported from reviewed source · Eligibility assessment <code>{{ sourceProvenance.assessmentHash }}</code></p></section><div v-if="actionError" class="source-error" role="alert"><strong>{{ actionError.title }}</strong><p>{{ actionError.message }}</p></div><StoryValidationSummary :issues="validationIssues" @focus="focusIssue" />
      <section class="studio-panel source-metadata"><fieldset><legend>Source identity</legend><p>These fields describe the original material from which Panda Pages editions are authored.</p><div class="source-metadata__grid"><label class="studio-field source-metadata__wide" for="source-title"><span>Original title</span><input id="source-title" :value="form.title" @input="update('title', ($event.target as HTMLInputElement).value)" /><small v-if="issuesByField.title?.length" class="studio-field__error">{{ issuesByField.title[0] }}</small></label><label class="studio-field" for="source-author"><span>Original author <small>Optional</small></span><input id="source-author" :value="form.author" @input="update('author', ($event.target as HTMLInputElement).value)" /></label><label class="studio-field" for="source-language"><span>Language</span><input id="source-language" :value="form.language" @input="update('language', ($event.target as HTMLInputElement).value)" /></label><label class="studio-field" for="source-rights"><span>Rights</span><input id="source-rights" :value="form.rightsLabel" placeholder="Public domain" @input="update('rightsLabel', ($event.target as HTMLInputElement).value)" /></label><label class="studio-field source-metadata__wide" for="source-url"><span>Source URL <small>Optional</small></span><input id="source-url" type="url" :value="form.sourceUrl" @input="update('sourceUrl', ($event.target as HTMLInputElement).value)" /></label></div></fieldset></section>
      <section class="studio-panel source-text-panel" aria-labelledby="source-text-title"><div class="source-text-panel__heading"><div><h2 id="source-text-title">Original source text</h2><p>The text is stored as canonical provenance, not as a Reader edition.</p></div><input id="source-file" class="studio-visually-hidden" type="file" accept=".txt,.md,.markdown,.html,.htm,text/plain,text/markdown,text/html" aria-label="Import canonical source file" @change="sourceFileChosen" /><button type="button" class="studio-button studio-button--quiet" @click="chooseSourceFile">Import file</button></div><p v-if="sourceFilename" class="source-file-note">Imported from <strong>{{ sourceFilename }}</strong>. No adaptation transforms were applied.</p><label class="studio-visually-hidden" for="source-text">Original source text</label><textarea id="source-text" :value="form.sourceText" spellcheck="true" placeholder="Paste or import the canonical original text…" @input="update('sourceText', ($event.target as HTMLTextAreaElement).value)" /><p v-if="issuesByField.sourceText?.length" class="studio-field__error">{{ issuesByField.sourceText[0] }}</p></section>
      <footer class="source-footer"><button type="button" class="studio-button studio-button--quiet" @click="router.push(`/admin/stories/${encodeURIComponent(slug)}`)">Return to story</button><button type="button" class="studio-button studio-button--primary" :disabled="saving" @click="saveSource">{{ saving ? 'Saving…' : 'Save source revision' }}</button></footer>
      <StoryStudioDialog :open="importDialogOpen" title="Replace the current source text?" description="This import will replace substantial unsaved canonical source text." confirm-label="Replace source text" danger @confirm="pendingImport && applySourceImport(pendingImport)" @cancel="importDialogOpen = false; pendingImport = null"><p>The imported file is not adapted, simplified or converted into a reading edition.</p></StoryStudioDialog>
    </template>
  </div>
</template>
<style scoped>
.source-provenance{margin-bottom:1rem}.source-provenance h2{font-family:var(--panda-serif);font-size:1.1rem}.source-provenance p{margin-top:.35rem;color:var(--studio-muted)}.source-heading{align-items:center}.source-dirty{width:fit-content;margin:-.5rem 0 1rem;border:1px solid var(--panda-warning);border-radius:var(--panda-radius-pill);background:var(--panda-warning-surface);color:var(--panda-warning);padding:.35rem .7rem;font-size:.78rem;font-weight:720}.source-error{margin-bottom:1rem;border:1px solid var(--panda-danger);border-radius:var(--panda-radius-card);background:var(--panda-danger-surface);color:var(--panda-danger);padding:.9rem 1rem}.source-error p{margin-top:.3rem}.source-metadata fieldset{border:0;padding:0}.source-metadata legend,.source-text-panel h2{font-family:var(--panda-serif);font-size:1.15rem;font-weight:650}.source-metadata fieldset>p,.source-text-panel__heading p{margin-top:.25rem;color:var(--studio-muted)}.source-metadata__grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;margin-top:1rem}.source-metadata__wide{grid-column:1/-1}.source-metadata input{width:100%;min-height:2.75rem;margin-top:.35rem;border:1px solid var(--studio-line-strong);border-radius:var(--panda-radius-compact);background:var(--panda-white);padding:.55rem .7rem}.source-text-panel{margin-top:1rem}.source-text-panel__heading{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem}.source-file-note{margin-top:.8rem;border-radius:var(--panda-radius-compact);background:var(--panda-mist);padding:.7rem .8rem;color:var(--studio-muted)}.source-text-panel textarea{display:block;width:100%;min-height:34rem;resize:vertical;margin-top:1rem;border:1px solid var(--studio-line-strong);border-radius:var(--panda-radius-compact);background:var(--panda-white);padding:1rem;font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;font-size:max(1rem,16px);line-height:1.6}.source-footer{display:flex;justify-content:flex-end;gap:.6rem;margin-top:1rem;border-top:1px solid var(--studio-line);padding-top:1rem}@media(max-width:620px){.source-heading,.source-text-panel__heading{align-items:stretch;flex-direction:column}.source-metadata__grid{grid-template-columns:1fr}.source-metadata__wide{grid-column:auto}.source-footer{display:grid;grid-template-columns:1fr}}
</style>
