import assert from 'node:assert/strict'
import test from 'node:test'
import { loadTypeScript } from './helpers/typescript-module.mjs'

const versionOne = '11111111-1111-4111-8111-111111111111'
const versionTwo = '22222222-2222-4222-8222-222222222222'
const sourceVersion = '33333333-3333-4333-8333-333333333333'
const timestamp = '2026-08-08T15:15:00Z'
const editionKeys = ['classic','confident-readers','growing-readers','story-explorers','little-listeners']
async function loadAPI(){const {module}=await loadTypeScript('../src/lib/api.ts',import.meta.url,(value)=>value.replaceAll('import.meta.env.VITE_API_BASE',"''"));return module}
function version(editionKey,id,number,overrides={}){return{editionKey,versionId:id,version:number,createdAt:timestamp,isDraft:false,isPublished:false,segmentCount:3,wordCount:21,chapterCount:1,health:'ready',...overrides}}
function edition(editionKey,status='empty',versions=[],publishedVersion=null,draftVersion=null){return{editionKey,status,publishedVersion,draftVersion,versionCount:versions.length,updatedAt:status==='empty'?null:timestamp,versions}}
function editions(classicVersions=[]){const draft=classicVersions.find((item)=>item.isDraft)??null;const published=classicVersions.find((item)=>item.isPublished)??null;return editionKeys.map((key)=>key==='classic'?edition(key,published?(draft&&draft.versionId!==published.versionId?'published_with_draft':'published'):draft?'draft_only':classicVersions.length?'unpublished':'empty',classicVersions,published?{versionId:published.versionId,version:published.version}:null,draft?{versionId:draft.versionId,version:draft.version}:null):edition(key))}
function summary(){const classicVersions=[version('classic',versionTwo,2,{isDraft:true}),version('classic',versionOne,1,{isPublished:true})];const slots=editions(classicVersions);return{slug:'contract-story',title:'Contract Story',author:'Panda Author',language:'en-GB',rights:{label:'Public domain'},sourceUrl:'https://example.invalid/source',status:'published_with_draft',publishedVersion:{versionId:versionOne,version:1},draftVersion:{versionId:versionTwo,version:2},versionCount:2,updatedAt:timestamp,currentRelease:{release:1,createdAt:timestamp,editions:[{editionKey:'classic',versionId:versionOne,version:1}]},releaseCount:1,source:{status:'ready',currentVersion:{versionId:sourceVersion,version:1},versionCount:1,updatedAt:timestamp},editions:slots.map((slot) => ({
      editionKey: slot.editionKey,
      status: slot.status,
      publishedVersion: slot.publishedVersion,
      draftVersion: slot.draftVersion,
      versionCount: slot.versionCount,
      updatedAt: slot.updatedAt,
    }))}}
function detail(){const classicVersions=[version('classic',versionTwo,2,{isDraft:true}),version('classic',versionOne,1,{isPublished:true})];return{...summary(),createdAt:timestamp,versions:classicVersions,editions:editions(classicVersions),releases:[summary().currentRelease]}}
function response(body,status=200){return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}})}

test('catalogue requires source state and exactly five ordered editions',async()=>{const api=await loadAPI();const parsed=api.parseAdminStoriesListResponse({items:[{...summary(),additive:{harmless:true}}]});assert.equal(parsed.items[0].source.status,'ready');assert.deepEqual(parsed.items[0].editions.map((item)=>item.editionKey),editionKeys);assert.equal('additive' in parsed.items[0],false);const wrong=structuredClone(summary());wrong.editions.reverse();assert.throws(()=>api.parseAdminStoriesListResponse({items:[wrong]}),/Invalid admin response/)})

test('detail makes edition-local history authoritative and ignores legacy top-level history',async()=>{const api=await loadAPI();const payload=detail();payload.versions=[{hostile:true}];const parsed=api.parseAdminStoryDetail(payload);assert.deepEqual(parsed.editions[0].versions.map((item)=>item.version),[2,1]);assert.equal('versions' in parsed,false);assert.equal(parsed.editions[1].status,'empty')})

test('edition source is explicit',async()=>{const api=await loadAPI();const source=api.parseAdminVersionSource({slug:'contract-story',editionKey:'growing-readers',versionId:versionTwo,version:2,title:'Contract Story',author:null,language:'en-GB',rights:{},sourceUrl:null,markdown:'# Contract Story\n\nReadable edition.\n',renderedHtml:'<h1>Contract Story</h1>',segmentCount:2,wordCount:4,chapterCount:0,createdAt:timestamp,isDraft:true,isPublished:false,health:'ready'});assert.equal(source.editionKey,'growing-readers')})

test('canonical source text is accepted only by the explicit source-version parser',async()=>{const api=await loadAPI();const detail=api.parseAdminSourceDetail({slug:'contract-story',status:'ready',currentVersion:{versionId:sourceVersion,version:1},versionCount:1,updatedAt:timestamp,versions:[{versionId:sourceVersion,version:1,title:'Original',author:'Author',language:'en',rights:{label:'Public domain'},sourceUrl:null,createdAt:timestamp,isCurrent:true}]});assert.equal(detail.versions[0].isCurrent,true);const raw='ORIGINAL\r\n\r\nCafé 世界\r\n';assert.equal(api.parseAdminSourceVersion({slug:'contract-story',versionId:sourceVersion,version:1,title:'Original',author:'Author',language:'en',rights:{label:'Public domain'},sourceUrl:null,sourceText:raw,createdAt:timestamp,isCurrent:true}).sourceText,raw);assert.throws(()=>api.parseAdminStoriesListResponse({items:[{...summary(),sourceText:'leak'}]}),/Invalid admin response/)})

test('draft response carries a finite edition key',async()=>{const api=await loadAPI();const draft=api.parseAdminDraftUpsertResponse({slug:'contract-story',editionKey:'little-listeners',versionId:versionTwo,version:2,segmentCount:2,wordCount:5,chapterCount:0,renderedHtml:'<h1>Contract Story</h1>',outcome:'created_version'});assert.equal(draft.editionKey,'little-listeners');assert.throws(()=>api.parseAdminDraftUpsertResponse({...draft,editionKey:'bedtime-ultra'}),/Invalid admin response/)})

test('edition/source wrappers use authoritative protected routes',async(t)=>{const originalFetch=globalThis.fetch;t.after(()=>{globalThis.fetch=originalFetch});const requests=[];globalThis.fetch=async(url,init)=>{requests.push({url:String(url),init});if(String(url).includes('/editions/'))return response({slug:'contract-story',editionKey:'growing-readers',versionId:versionTwo,version:2,title:'Contract Story',author:null,language:'en-GB',rights:{},sourceUrl:null,markdown:'# Contract Story',renderedHtml:'<h1>Contract Story</h1>',segmentCount:1,wordCount:2,chapterCount:0,createdAt:timestamp,isDraft:true,isPublished:false,health:'ready'});if(String(url).endsWith('/source')&&init.method==='PUT')return response({slug:'contract-story',versionId:sourceVersion,version:1,outcome:'created_source'});if(String(url).includes('/source/versions/'))return response({slug:'contract-story',versionId:sourceVersion,version:1,title:'Original',author:null,language:'en-GB',rights:{},sourceUrl:null,sourceText:'Original source',createdAt:timestamp,isCurrent:true});if(String(url).endsWith('/source'))return response({slug:'contract-story',status:'ready',currentVersion:{versionId:sourceVersion,version:1},versionCount:1,updatedAt:timestamp,versions:[{versionId:sourceVersion,version:1,title:'Original',author:null,language:'en-GB',rights:{},sourceUrl:null,createdAt:timestamp,isCurrent:true}]});if(String(url).endsWith('/releases'))return response({slug:'contract-story',outcome:'created',release:{release:2,createdAt:timestamp,editions:[{editionKey:'classic',versionId:versionOne,version:1}]}});if(String(url).endsWith('/unpublish'))return response({slug:'contract-story',status:'draft_only',publishedVersion:null,draftVersion:{versionId:versionTwo,version:2},versionCount:2,updatedAt:timestamp,currentRelease:null,releaseCount:2});return response(detail())};const api=await loadAPI();await api.adminGetStory('contract-story');await api.adminGetEditionVersionSource('contract-story','growing-readers',versionTwo);await api.adminGetSource('contract-story');await api.adminGetSourceVersion('contract-story',sourceVersion);await api.adminUpsertSource('contract-story',{title:'Original',author:null,language:'en-GB',sourceUrl:null,rights:{},sourceText:'Original source'});await api.adminCreateRelease('contract-story',{editions:[{editionKey:'classic',versionId:versionOne}]});await api.adminUnpublishStory('contract-story');assert.deepEqual(requests.map(({url})=>url),['/api/v1/admin/stories/contract-story',`/api/v1/admin/stories/contract-story/editions/growing-readers/versions/${versionTwo}`,'/api/v1/admin/stories/contract-story/source',`/api/v1/admin/stories/contract-story/source/versions/${sourceVersion}`,'/api/v1/admin/stories/contract-story/source','/api/v1/admin/stories/contract-story/releases','/api/v1/admin/stories/contract-story/unpublish']);assert.ok(requests.every(({init})=>init.credentials==='omit'))})

test('validation issues and HTTP failure classes stay typed',async(t)=>{const originalFetch=globalThis.fetch;t.after(()=>{globalThis.fetch=originalFetch});const api=await loadAPI();globalThis.fetch=async()=>response({error:{code:'preview_invalid',message:'Story content is invalid',issues:[{field:'title',code:'required',message:'Enter a title'}]}},400);let caught;try{await api.adminPreview({slug:'contract-story',editionKey:'story-explorers',title:'',markdown:'# Contract Story'})}catch(error){caught=error}assert.deepEqual(api.getAdminValidationIssues(caught),[{field:'title',code:'required',message:'Enter a title'}]);for(const [status,code] of [[401,'unauthorized'],[403,'forbidden'],[409,'draft_repair_required'],[500,'draft_failed']]){globalThis.fetch=async()=>response({error:{code,message:`status ${status}`}},status);await assert.rejects(api.adminDraftUpsertStory({slug:'contract-story',editionKey:'classic',title:'Contract Story',markdown:'# Contract Story'}),(error)=>error.status===status&&error.code===code)}})
