#!/usr/bin/env bash

set -euo pipefail
umask 077

repo_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
backup_script="$repo_root/scripts/postgresql-backup.sh"
restore_verify_script="$repo_root/scripts/postgresql-backup-restore-verify.sh"
restore_rehearsal_script="$repo_root/scripts/postgresql-restore-rehearsal.sh"
readonly postgres_image='postgres:18.1-alpine@sha256:b40d931bd0e7ce6eecc59a5a6ac3b3c04a01e559750e73e7086b6dbd7f8bf545'

for command_name in docker mktemp sha256sum sort tail tar; do
  command -v "$command_name" >/dev/null 2>&1 || {
    printf 'Required command is unavailable: %s\n' "$command_name" >&2
    exit 1
  }
done

if [[ -n ${DOCKER_HOST:-} ]]; then
  printf 'Refusing integration test while DOCKER_HOST is set\n' >&2
  exit 1
fi

docker_context=$(docker context show)
docker_endpoint=$(docker context inspect "$docker_context" --format '{{.Endpoints.docker.Host}}')
if [[ "$docker_context" != default && "$docker_context" != desktop-linux ]] || [[ "$docker_endpoint" != unix://* ]]; then
  printf 'Integration test requires a known local Docker Unix socket\n' >&2
  exit 1
fi

test_root=$(mktemp -d "${TMPDIR:-/tmp}/pandapages-backup-integration.XXXXXX")
resource_prefix="pandapages-pg-backup-integration-$$"
source_container="$resource_prefix-source"
source_network="$resource_prefix-network"
source_volume="$resource_prefix-data"
source_created=false
network_created=false
volume_created=false

cleanup() {
  set +e
  if $source_created; then
    docker rm --force "$source_container" >/dev/null 2>&1
  fi
  if $network_created; then
    docker network rm "$source_network" >/dev/null 2>&1
  fi
  if $volume_created; then
    docker volume rm "$source_volume" >/dev/null 2>&1
  fi
  rm -rf -- "$test_root"
}
trap cleanup EXIT

before_rehearsal_resources="$test_root/before-rehearsal-resources"
docker ps -aq --filter label=com.pandapages.disposable=restore-rehearsal | sort \
  >"$before_rehearsal_resources"

secret_dir="$test_root/secret"
mkdir -p "$secret_dir"
password_file="$secret_dir/postgres-password"
printf 'generated-integration-password-not-for-production\n' >"$password_file"
chmod 0600 "$password_file"

docker network create --internal \
  --label com.pandapages.disposable=backup-integration \
  "$source_network" >/dev/null
network_created=true
docker volume create \
  --label com.pandapages.disposable=backup-integration \
  "$source_volume" >/dev/null
volume_created=true

docker run --detach \
  --name "$source_container" \
  --network "$source_network" \
  --read-only \
  --security-opt no-new-privileges \
  --tmpfs /tmp:rw,nosuid,nodev,noexec,size=64m \
  --tmpfs /var/run/postgresql:rw,nosuid,nodev,noexec,size=16m \
  --label com.pandapages.disposable=backup-integration \
  --env POSTGRES_USER=postgres \
  --env POSTGRES_DB=pandapages_test \
  --env POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password \
  --env POSTGRES_INITDB_ARGS=--data-checksums \
  --mount "type=volume,src=$source_volume,dst=/var/lib/postgresql" \
  --mount "type=bind,src=$password_file,dst=/run/secrets/postgres-password,readonly" \
  --health-cmd 'pg_isready --username=postgres --dbname=pandapages_test' \
  --health-interval 1s \
  --health-timeout 3s \
  --health-retries 60 \
  "$postgres_image" >/dev/null
source_created=true

health=starting
for ((attempt = 0; attempt < 60; attempt++)); do
  health=$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$source_container")
  [[ "$health" == healthy ]] && break
  [[ "$health" != unhealthy ]] || {
    printf 'Generated source PostgreSQL became unhealthy\n' >&2
    exit 1
  }
  sleep 1
done
[[ "$health" == healthy ]] || {
  printf 'Timed out waiting for generated source PostgreSQL\n' >&2
  exit 1
}

docker exec -i "$source_container" \
  psql -X --username=postgres --dbname=pandapages_test --set=ON_ERROR_STOP=1 <<'SQL' >/dev/null
CREATE EXTENSION pgcrypto;

CREATE ROLE pandapages_backup
  LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION;
GRANT pg_read_all_data TO pandapages_backup;
GRANT CONNECT ON DATABASE pandapages_test TO pandapages_backup;

CREATE TABLE story_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  markdown text NOT NULL
);

CREATE TABLE stories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  published_version_id bigint REFERENCES story_versions(id)
);

CREATE INDEX story_versions_markdown_length_idx
  ON story_versions ((char_length(markdown)));

INSERT INTO story_versions (markdown)
VALUES ('A generated plain-text story.'),
       ('Pöndá reads 世界 stories 🐼');

INSERT INTO stories (published_version_id)
SELECT id FROM story_versions ORDER BY id LIMIT 1;
SQL

fake_bin="$test_root/bin"
remote_root="$test_root/remote"
state_dir="$test_root/state"
lock_dir="$test_root/lock"
tmp_parent="$test_root/tmp"
mkdir -p "$fake_bin" "$remote_root/postgresql" "$state_dir" "$lock_dir" "$tmp_parent"

cat >"$fake_bin/age" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
if [[ ${1:-} == --version ]]; then
  printf 'v1.3.1\n'
  exit 0
fi
mode=""
output=""
key_file=""
input=""
while (($# > 0)); do
  case "$1" in
    --encrypt) mode=encrypt; shift ;;
    --decrypt) mode=decrypt; shift ;;
    --recipients-file|--identity) key_file=${2:?}; shift 2 ;;
    --output) output=${2:?}; shift 2 ;;
    *) input=$1; shift ;;
  esac
done
[[ -s "$key_file" && -n "$output" && -f "$input" ]]
if [[ "$mode" == encrypt ]]; then
  { printf 'FAKE-AGE-INTEGRATION-HEADER\n'; cat "$input"; } >"$output"
elif [[ "$mode" == decrypt ]]; then
  read -r header <"$input"
  [[ "$header" == FAKE-AGE-INTEGRATION-HEADER ]]
  tail -n +2 "$input" >"$output"
else
  exit 1
fi
EOF

cat >"$fake_bin/rclone" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
if [[ ${1:-} == version ]]; then
  printf 'rclone v1.74.4\n'
  exit 0
fi
if [[ ${1:-} == config && ${2:-} == redacted ]]; then
  printf '[fake]\ntype = s3\n'
  exit 0
fi

command_name=${1:?}
shift
operands=()
include_pattern=""
while (($# > 0)); do
  case "$1" in
    --config|--include)
      [[ "$1" != --include ]] || include_pattern=${2:?}
      shift 2
      ;;
    --immutable|--no-traverse|--files-only) shift ;;
    *) operands+=("$1"); shift ;;
  esac
done
map_path() {
  if [[ "$1" == fake:* ]]; then
    printf '%s/%s\n' "$FAKE_REMOTE_ROOT" "${1#fake:}"
  else
    printf '%s\n' "$1"
  fi
}
case "$command_name" in
  copyto)
    source_path=$(map_path "${operands[0]}")
    destination_path=$(map_path "${operands[1]}")
    mkdir -p "$(dirname -- "$destination_path")"
    cp -- "$source_path" "$destination_path"
    ;;
  deletefile)
    rm -f -- "$(map_path "${operands[0]}")"
    ;;
  lsf)
    directory=$(map_path "${operands[0]}")
    shopt -s nullglob
    for path in "$directory"/*; do
      filename=${path##*/}
      if [[ -z "$include_pattern" || "$filename" == $include_pattern ]]; then
        printf '%s\n' "$filename"
      fi
    done
    ;;
  *) exit 1 ;;
esac
EOF
chmod 0755 "$fake_bin/age" "$fake_bin/rclone"

rclone_config="$test_root/rclone.conf"
recipients_file="$test_root/recipients.txt"
identities_file="$test_root/identities.txt"
printf '[fake]\ntype = local\n' >"$rclone_config"
printf 'age1integrationrecipient\n' >"$recipients_file"
printf 'AGE-SECRET-KEY-INTEGRATION-ONLY\n' >"$identities_file"
chmod 0600 "$rclone_config" "$recipients_file" "$identities_file"

environment=(
  "PATH=$fake_bin:$PATH"
  "FAKE_REMOTE_ROOT=$remote_root"
  "PP_BACKUP_POSTGRES_CONTAINER=$source_container"
  "PP_BACKUP_DATABASE=pandapages_test"
  "PP_BACKUP_DATABASE_USER=pandapages_backup"
  "PP_BACKUP_GLOBALS_USER=postgres"
  "PP_BACKUP_REMOTE=fake:postgresql"
  "PP_BACKUP_RCLONE_CONFIG=$rclone_config"
  "PP_BACKUP_AGE_RECIPIENTS_FILE=$recipients_file"
  "PP_BACKUP_AGE_IDENTITIES_FILE=$identities_file"
  "PP_BACKUP_STATE_DIR=$state_dir"
  "PP_BACKUP_LOCK_DIR=$lock_dir"
  "PP_BACKUP_TMP_PARENT=$tmp_parent"
  "PP_BACKUP_EXPECT_AGE_VERSION=1.3.1"
  "PP_BACKUP_EXPECT_RCLONE_VERSION=1.74.4"
  "PP_BACKUP_POSTGRES_IMAGE=$postgres_image"
  "PP_BACKUP_TEST_MODE=true"
)

printf '1..3\n'

env "${environment[@]}" PP_BACKUP_TEST_NOW_UTC=20260713T031700Z \
  "$backup_script" >"$test_root/backup.out"
env "${environment[@]}" \
  "$restore_verify_script" >"$test_root/restore.out"

grep -qx 'result=success' "$test_root/backup.out"
grep -qx 'disposable_restore_verified=true' "$test_root/restore.out"
grep -qx 'plaintext_cleanup=complete' "$test_root/restore.out"
printf 'ok 1 - generated PostgreSQL data completes backup and disposable restore\n'

encrypted_backup="$remote_root/postgresql/pandapages-postgresql-20260713T031700Z.tar.age"
archive_path="$test_root/generated-backup.tar"
tail -n +2 "$encrypted_backup" >"$archive_path"
extracted="$test_root/extracted"
mkdir -p "$extracted"
tar --extract --file "$archive_path" --directory "$extracted"
printf 'required_missing_extension|1.0\n' >>"$extracted/expectations/extensions.tsv"

if "$restore_rehearsal_script" \
  --dump "$extracted/database.dump" \
  --report-dir "$test_root/missing-extension-report" \
  --expected-row-counts "$extracted/expectations/row-counts.tsv" \
  --expected-metadata-dir "$extracted/expectations" \
  --image "$postgres_image" \
  >"$test_root/missing-extension.out" 2>"$test_root/missing-extension.err"; then
  printf 'Missing required extension was unexpectedly accepted\n' >&2
  exit 1
fi
printf 'ok 2 - disposable restore rejects a missing required extension\n'

after_rehearsal_resources="$test_root/after-rehearsal-resources"
docker ps -aq --filter label=com.pandapages.disposable=restore-rehearsal | sort \
  >"$after_rehearsal_resources"
diff -u "$before_rehearsal_resources" "$after_rehearsal_resources"
if compgen -G "$tmp_parent/pandapages-postgresql-*" >/dev/null; then
  printf 'Backup or restore plaintext temporary directory remained\n' >&2
  exit 1
fi
printf 'ok 3 - generated tests leave no disposable restore resources or plaintext\n'
