<script setup lang="ts">
import PublicInfoLayout from '../components/app/PublicInfoLayout.vue'
</script>

<template>
  <PublicInfoLayout title="Content & Copyright" summary="How Panda Pages approaches reading editions, source information, and content concerns.">
    <section aria-labelledby="content-overview"><h2 id="content-overview">Content on Panda Pages</h2><p>Panda Pages can provide reading editions and Story Studio content. Material can have different origins and rights positions, so it should not be assumed that every story has the same copyright status.</p></section>
    <section aria-labelledby="content-public-domain"><h2 id="content-public-domain">Public-domain source works</h2><p>Some reading material may derive from public-domain literature. Whether a source work is public domain can depend on the original work, a particular edition, translation, adaptation, illustration, and the jurisdiction in question. An older work is not necessarily unrestricted everywhere.</p></section>
    <section aria-labelledby="content-adaptations"><h2 id="content-adaptations">Panda Pages adaptations</h2><p>Panda Pages may prepare reading editions by shortening, rewriting, restructuring, adjusting vocabulary, changing narrative scope, or adapting material for a reading level. A public-domain source work does not necessarily mean that the displayed Panda Pages adaptation is a verbatim public-domain text. Panda Pages does not claim ownership of source works simply because it presents an adaptation.</p></section>
    <section aria-labelledby="content-story-studio"><h2 id="content-story-studio">Story Studio supplied material</h2><p>Authenticated adults can use Story Studio to create or import material. Supported information can include text, Markdown, HTML, title, author, language, source URL, source text, rights metadata, editions, versions, and releases. Account holders should provide only material they are entitled to use. Formal upload licences, warranties, and service terms will be addressed separately.</p></section>
    <section aria-labelledby="content-provenance"><h2 id="content-provenance">Source and provenance information</h2><p>Panda Pages may record source title, author, language, rights information, source URL, and source versions where available. This helps maintain provenance, but rights metadata is information rather than a legal guarantee. Not every story necessarily displays every provenance field publicly, and Panda Pages does not claim to have independently legally verified every rights entry.</p></section>
    <section aria-labelledby="content-copyright-concerns"><h2 id="content-copyright-concerns">Copyright and attribution concerns</h2><p>Panda Pages is UK-operated. Concerns may include suspected copyright infringement, incorrect author attribution, incorrect source information, or other rights and provenance issues. Contact details for general content and copyright reports will be provided through Panda Pages support.</p></section>
    <section aria-labelledby="content-other-concerns"><h2 id="content-other-concerns">Other content concerns</h2><p>Future Panda Pages support contact details will also cover unsuitable content, factual or editorial issues, formatting or import problems, and accessibility concerns. We do not currently provide a separate reporting backend or a US-specific DMCA process.</p></section>
    <section aria-labelledby="content-privacy"><h2 id="content-privacy">Privacy</h2><p>For privacy, individual-rights, or account-deletion enquiries, contact <a href="mailto:privacy@southcoastapps.co.uk">privacy@southcoastapps.co.uk</a>. Read the <a href="/privacy">Panda Pages Privacy Policy</a> for information about how Panda Pages handles personal information.</p></section>
  </PublicInfoLayout>
</template>

<style scoped>
section{margin-top:2.5rem;scroll-margin-top:1rem}section>:first-child{margin-top:0}h2{margin-bottom:.75rem;font-family:var(--panda-serif);font-size:clamp(1.35rem,4vw,1.8rem);font-weight:680;letter-spacing:-.025em;line-height:1.18}p{color:var(--panda-soft-ink);font-size:1rem;line-height:1.7}a{color:var(--panda-ink);font-weight:750;text-decoration-thickness:.08em;text-underline-offset:.16em}a:focus-visible{outline:3px solid var(--panda-focus);outline-offset:3px}@media(forced-colors:active){p{color:CanvasText}a{color:LinkText}}
</style>
