<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import PandaAuthShell from "../components/app/PandaAuthShell.vue";
import { listReaderProfiles, logout as logoutSession, type ReaderProfile } from "../lib/api";
import { currentAccountContext } from "../lib/account-context";
import { readerEditionLabel } from "../lib/reader-editions";
const router=useRouter(); const profiles=ref<readonly ReaderProfile[]>([]); const loading=ref(true); const errorMessage=ref(""); const signingOut=ref(false); const canSwitchAccount=ref(false); const canOpenStoryStudio=ref(false); const accountName=ref(""); const principalName=ref(""); const accountRole=ref<"owner"|"adult"|null>(null); const accountRoleLabel=computed(()=>accountRole.value==="owner"?"Owner":"Adult member");
async function refresh(){const account=await currentAccountContext(); profiles.value=await listReaderProfiles(account);canSwitchAccount.value=account.identity.memberships.length>1;canOpenStoryStudio.value=account.membership.role==="owner";accountName.value=account.membership.accountName;principalName.value=account.identity.principal.displayName;accountRole.value=account.membership.role;}
async function signOut(){if(signingOut.value)return;signingOut.value=true;try{await logoutSession();await router.replace("/account/login");}catch{errorMessage.value="Sign-out could not be completed. Your Panda Pages account is still open.";}finally{signingOut.value=false;}}
onMounted(async()=>{try{await refresh();}catch(error){errorMessage.value=error instanceof Error&&error.message?error.message:"Profiles could not be loaded. Please try again.";}finally{loading.value=false;}});
</script>
<template><PandaAuthShell eyebrow="Parent area" title="Manage profiles" description="Update reader settings without starting a reading session."><p v-if="loading" role="status">Loading profiles…</p><p v-else-if="errorMessage" class="error" role="alert">{{ errorMessage }}</p><div v-else class="manage"><div class="actions"><button type="button" @click="router.push('/profiles')">Back to Who’s reading?</button><button type="button" @click="router.push({path:'/profiles/new',query:{from:'manage'}})">Add profile</button></div><p v-if="profiles.length===0">There are no reader profiles yet.</p><ul v-else aria-label="Reader profiles"><li v-for="profile in profiles" :key="profile.id"><div><strong>{{profile.name}}</strong><span>Reading level: {{readerEditionLabel(profile.readingLevel)}}</span><span v-if="profile.pinEnabled">PIN protected</span></div><button type="button" @click="router.push(`/profiles/${encodeURIComponent(profile.id)}/edit`)">Edit {{profile.name}}</button></li></ul><section class="utilities" aria-labelledby="account-heading"><h2 id="account-heading">Account</h2><p>{{accountName}} · Signed in as {{principalName}} · {{accountRoleLabel}}</p><div class="actions"><button v-if="canSwitchAccount" type="button" @click="router.push('/account')">Switch account</button><button v-if="canOpenStoryStudio" type="button" @click="router.push('/admin/stories')">Story Studio</button><button type="button" :disabled="signingOut" @click="signOut">{{signingOut?'Signing out…':'Sign out'}}</button></div></section></div></PandaAuthShell></template>
<style scoped>.manage,.utilities{display:grid;gap:1rem}.actions{display:flex;flex-wrap:wrap;gap:.65rem}ul{display:grid;gap:.75rem;margin:0;padding:0;list-style:none}li,.utilities{border:1px solid var(--panda-line-strong);border-radius:var(--panda-radius-compact);padding:.9rem}li{display:flex;align-items:center;justify-content:space-between;gap:1rem}li div{display:grid;gap:.25rem}li span,.utilities p{color:var(--panda-muted);font-size:.86rem}.utilities h2,.utilities p{margin:0}.error{margin:0;color:var(--panda-danger,#8b1e1e);font-weight:700}button{min-height:2.7rem;border:1px solid var(--panda-ink);border-radius:var(--panda-radius-compact);padding:.55rem .85rem;background:var(--panda-paper-raised);color:var(--panda-ink);font:inherit;font-weight:750}@media(max-width:28rem){li{align-items:stretch;flex-direction:column}li button{width:100%}}</style>
