<script setup lang="ts">
import { nextTick, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import PandaAuthShell from "../components/app/PandaAuthShell.vue";
import ProfileFields from "../components/profile/ProfileFields.vue";
import { deleteReaderProfile, getAPIErrorStatus, listReaderProfiles, removeReaderProfilePIN, renameReaderProfile, setReaderProfilePIN, type ReaderEditionKey, type ReaderProfile } from "../lib/api";
import { currentAccountContext } from "../lib/account-context";
import { invalidateReaderProfileSession } from "../lib/profile-session";
const route=useRoute(),router=useRouter(),profile=ref<ReaderProfile|null>(null),name=ref(""),readingLevel=ref<ReaderEditionKey>("classic"),loading=ref(true),busy=ref(false),errorMessage=ref(""),pinDialog=ref<"set"|"remove"|null>(null),pinValue=ref(""),pinError=ref(""),deleteOpen=ref(false),deleteConfirm=ref<HTMLButtonElement|null>(null);const id=()=>typeof route.params.profileID==="string"?route.params.profileID:"";const message=(e:unknown)=>e instanceof Error&&e.message?e.message:"Profile could not be updated. Please try again.";
async function load(){const account=await currentAccountContext();const found=(await listReaderProfiles(account)).find(x=>x.id===id());if(!found){await router.replace("/profiles/manage");return;}profile.value=found;name.value=found.name;readingLevel.value=found.readingLevel;} async function save(){if(!profile.value||busy.value)return;busy.value=true;errorMessage.value="";try{await renameReaderProfile(profile.value.id,name.value,readingLevel.value);await router.replace("/profiles/manage");}catch(e){errorMessage.value=message(e);}finally{busy.value=false;}}function closePIN(){pinDialog.value=null;pinValue.value="";pinError.value="";}async function submitPIN(){if(!profile.value||busy.value)return;busy.value=true;pinError.value="";try{await setReaderProfilePIN(profile.value.id,pinValue.value);await load();closePIN();}catch(e){pinError.value=getAPIErrorStatus(e)===429?"Too many tries. Please wait before trying again.":message(e);}finally{busy.value=false;}}async function removePIN(){if(!profile.value||busy.value)return;busy.value=true;try{await removeReaderProfilePIN(profile.value.id);await load();closePIN();}catch(e){errorMessage.value=message(e);}finally{busy.value=false;}}async function confirmDelete(){deleteOpen.value=true;await nextTick();deleteConfirm.value?.focus();}async function deleteProfile(){if(!profile.value||busy.value)return;busy.value=true;try{await deleteReaderProfile(profile.value.id);invalidateReaderProfileSession(profile.value.id);await router.replace("/profiles/manage");}catch(e){errorMessage.value=message(e);}finally{busy.value=false;}}onMounted(async()=>{try{await load();}catch(e){errorMessage.value=message(e);}finally{loading.value=false;}});
</script>
<template><PandaAuthShell eyebrow="Profiles" :title="profile?`Edit ${profile.name}`:'Edit profile'"><p v-if="loading" role="status">Loading profile…</p><p v-else-if="errorMessage&&!profile" class="error" role="alert">{{errorMessage}}</p><div v-else-if="profile" class="edit"><form class="form" @submit.prevent="save"><ProfileFields v-model:name="name" v-model:reading-level="readingLevel" name-id="profile-name" level-id="profile-level" :disabled="busy"/><p v-if="errorMessage" class="error" role="alert">{{errorMessage}}</p><div class="actions"><button type="button" :disabled="busy" @click="router.push('/profiles/manage')">Cancel</button><button type="submit" :disabled="busy">{{busy?'Saving…':'Save profile'}}</button></div></form><section class="settings"><h2>PIN</h2><p>{{profile.pinEnabled?'This reader needs a PIN to enter.':'This reader has no PIN.'}}</p><div class="actions"><button type="button" :disabled="busy" @click="pinDialog='set'">{{profile.pinEnabled?'Change PIN':'Set PIN'}}</button><button v-if="profile.pinEnabled" type="button" :disabled="busy" @click="pinDialog='remove'">Remove PIN</button></div></section><section class="settings"><h2>Delete profile</h2><p>Deleting a reader cannot be undone.</p><button type="button" class="danger" :disabled="busy" @click="confirmDelete">Delete profile</button></section></div><section v-if="pinDialog==='set'" class="dialog" role="dialog" aria-modal="true" aria-labelledby="pin-title"><h2 id="pin-title">{{profile?.pinEnabled?'Change':'Set'}} {{profile?.name}}’s PIN</h2><form class="form" @submit.prevent="submitPIN"><label for="profile-pin">Four-digit PIN</label><input id="profile-pin" v-model="pinValue" type="password" inputmode="numeric" autocomplete="off" pattern="[0-9]{4}" minlength="4" maxlength="4" :disabled="busy" required/><p v-if="pinError" class="error" role="alert">{{pinError}}</p><div class="actions"><button type="button" :disabled="busy" @click="closePIN">Cancel</button><button type="submit" :disabled="busy">Save PIN</button></div></form></section><section v-if="pinDialog==='remove'" class="dialog" role="alertdialog" aria-modal="true" aria-labelledby="remove-title"><h2 id="remove-title">Remove {{profile?.name}}’s PIN?</h2><p>Anyone using this account can enter this reader without a PIN.</p><div class="actions"><button type="button" :disabled="busy" @click="closePIN">Cancel</button><button type="button" class="danger" :disabled="busy" @click="removePIN">Remove PIN</button></div></section><section v-if="deleteOpen" class="dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-title"><h2 id="delete-title">Delete {{profile?.name}}?</h2><p>This removes this reader from the account. It cannot be undone.</p><div class="actions"><button type="button" :disabled="busy" @click="deleteOpen=false">Cancel</button><button ref="deleteConfirm" type="button" class="danger" :disabled="busy" @click="deleteProfile">Delete profile</button></div></section></PandaAuthShell></template>
<style scoped>.edit,.form,.settings,.dialog{display:grid;gap:1rem}.settings,.dialog{border:1px solid var(--panda-line-strong);border-radius:var(--panda-radius-compact);padding:.9rem}.settings h2,.settings p,.dialog h2,.dialog p{margin:0}.settings p{color:var(--panda-muted)}.actions{display:flex;flex-wrap:wrap;gap:.65rem}.error{margin:0;color:var(--panda-danger,#8b1e1e);font-weight:700}.danger{color:var(--panda-danger,#8b1e1e)}button,input{min-height:2.7rem;border:1px solid var(--panda-ink);border-radius:var(--panda-radius-compact);padding:.55rem .85rem;background:var(--panda-paper-raised);color:var(--panda-ink);font:inherit;font-weight:750}button[type="submit"]{background:var(--panda-ink);color:var(--panda-white)}input{border-color:var(--panda-line-strong);font-weight:400}</style>
