<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import PandaAuthShell from "../components/app/PandaAuthShell.vue";
import { getAPIErrorStatus, listReaderProfiles, type ReaderProfile, verifyReaderProfilePIN } from "../lib/api";
import { currentAccountContext } from "../lib/account-context";
import { resolveReaderDestination } from "../lib/profile-destination";
import { enterReaderProfileSession } from "../lib/profile-session";
import { clearSelectedReaderProfile, reconcileReaderProfileSelection, selectedReaderProfileID } from "../lib/reader-profile-selection";
const route=useRoute();const router=useRouter();const profiles=ref<readonly ReaderProfile[]>([]);const selectedID=ref<string|null>(null);const loading=ref(true);const busy=ref(false);const errorMessage=ref("");const pinTarget=ref<ReaderProfile|null>(null);const pinValue=ref("");const pinError=ref("");const unavailable=computed(()=>route.query.unavailable==='1');
const destination=()=>resolveReaderDestination(route.query.next);const message=(error:unknown)=>error instanceof Error&&error.message?error.message:"Profiles could not be updated. Please try again.";
function restore(){const value=reconcileReaderProfileSelection(selectedReaderProfileID(),profiles.value);if(!value){clearSelectedReaderProfile();selectedID.value=null;return;}selectedID.value=value.id;}
async function refresh(){profiles.value=await listReaderProfiles(await currentAccountContext());restore();}
async function choose(profile:ReaderProfile){if(profile.pinEnabled){pinTarget.value=profile;pinValue.value="";pinError.value="";return;}if(!enterReaderProfileSession(profile.id)){errorMessage.value="This reader could not be started. Please try again.";return;}selectedID.value=profile.id;await router.replace(destination());}
function closePIN(){pinTarget.value=null;pinValue.value="";pinError.value="";}
async function submitPIN(){const profile=pinTarget.value;if(!profile||busy.value)return;busy.value=true;pinError.value="";try{await verifyReaderProfilePIN(profile.id,pinValue.value);if(!enterReaderProfileSession(profile.id)){pinError.value="This reader could not be started. Please try again.";return;}selectedID.value=profile.id;closePIN();await router.replace(destination());}catch(error){pinError.value=getAPIErrorStatus(error)===429?"Too many tries. Please wait before trying again.":"That PIN is not right.";}finally{busy.value=false;}}
onMounted(async()=>{try{await refresh();}catch(error){errorMessage.value=message(error);}finally{loading.value=false;}});
</script>
<template><PandaAuthShell eyebrow="Profiles" title="Who’s reading?" description="Choose a reader to start a story."><p v-if="loading" role="status">Loading readers…</p><p v-else-if="errorMessage" class="error" role="alert">{{errorMessage}}</p><div v-else class="profiles"><p v-if="unavailable" class="notice" role="status">Readers could not be checked just now. Choose one when the connection is available.</p><p v-if="profiles.length===0">Add the first reader for this account.</p><ul v-else aria-label="Readers"><li v-for="profile in profiles" :key="profile.id"><div><h2>{{profile.name}}</h2><p>Reading level: {{profile.readingLevel}}</p><span v-if="profile.pinEnabled">PIN protected</span><span v-if="selectedID===profile.id">Selected</span></div><button type="button" :aria-label="`Start reading as ${profile.name}`" @click="choose(profile)">Start reading</button></li></ul><div class="actions"><button type="button" @click="router.push({path:'/profiles/new',query:{from:'chooser'}})">Add profile</button><button type="button" @click="router.push('/profiles/manage')">Manage profiles</button></div></div><section v-if="pinTarget" class="dialog" role="dialog" aria-modal="true" aria-labelledby="profile-pin-title"><h2 id="profile-pin-title">Enter {{pinTarget.name}}’s PIN</h2><form class="form" @submit.prevent="submitPIN"><label for="profile-pin">Four-digit PIN</label><input id="profile-pin" v-model="pinValue" type="password" inputmode="numeric" autocomplete="off" pattern="[0-9]{4}" minlength="4" maxlength="4" :disabled="busy" required/><p v-if="pinError" class="error" role="alert">{{pinError}}</p><div class="actions"><button type="button" :disabled="busy" @click="closePIN">Cancel</button><button type="submit" :disabled="busy">Continue</button></div></form></section></PandaAuthShell></template>
<style scoped>.profiles,.form,.dialog{display:grid;gap:1rem}ul{display:grid;gap:.75rem;margin:0;padding:0;list-style:none}li,.dialog{border:1px solid var(--panda-line-strong);border-radius:var(--panda-radius-compact);padding:.9rem}li{display:flex;align-items:center;justify-content:space-between;gap:1rem}h2,p{margin:0}li div{display:grid;gap:.3rem}li p,.notice{color:var(--panda-muted)}li span{font-size:.8rem;font-weight:700}.actions{display:flex;flex-wrap:wrap;gap:.65rem}.error{margin:0;color:var(--panda-danger,#8b1e1e);font-weight:700}button,input{min-height:2.7rem;border:1px solid var(--panda-ink);border-radius:var(--panda-radius-compact);padding:.55rem .85rem;background:var(--panda-paper-raised);color:var(--panda-ink);font:inherit;font-weight:750}li button,.actions button:last-child{background:var(--panda-ink);color:var(--panda-white)}input{border-color:var(--panda-line-strong);font-weight:400}@media(max-width:28rem){li{align-items:stretch;flex-direction:column}li button{width:100%}}</style>
