import { expect, test } from './support/auth'
import type { Route } from '@playwright/test'

const timestamp='2026-08-08T17:00:00Z'
const keys=['classic','confident-readers','growing-readers','story-explorers','little-listeners'] as const
const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444','55555555-5555-4555-8555-555555555555']
function ingestResponse(){return{slug:'five-friends',results:keys.map((editionKey,index)=>({editionKey,versionId:ids[index],version:index+1,segmentCount:2,wordCount:6,chapterCount:0,outcome:'created'}))}}
function storyDetail(){const editions=keys.map((editionKey,index)=>({editionKey,status:'draft_only',publishedVersion:null,draftVersion:{versionId:ids[index],version:index+1},versionCount:1,updatedAt:timestamp,versions:[{editionKey,versionId:ids[index],version:index+1,createdAt:timestamp,isDraft:true,isPublished:false,segmentCount:2,wordCount:6,chapterCount:0,health:'ready'}]}));return{slug:'five-friends',title:'Five Friends',author:null,language:'en-GB',rights:{},sourceUrl:null,status:'draft_only',publishedVersion:null,draftVersion:{versionId:ids[0],version:1},versionCount:1,createdAt:timestamp,updatedAt:timestamp,source:{status:'missing',currentVersion:null,versionCount:0,updatedAt:null},editions}}
function editionFiles(count=5){return keys.slice(0,count).map((editionKey)=>({name:`${editionKey}.md`,mimeType:'text/markdown',buffer:Buffer.from(`# Five Friends\n\n${editionKey} edition body.\n`,'utf8')}))}

test('owner ingests the exact five files in one draft-only bundle',async({page,auth})=>{const requests:Array<{method:string;path:string;body:unknown}>=[];await page.route('**/api/v1/admin/**',async(route:Route)=>{auth.assertApplicationRequest(route);const request=route.request();const path=new URL(request.url()).pathname;const method=request.method();const body=request.postDataJSON()??null;requests.push({method,path,body});if(method==='POST'&&path==='/api/v1/admin/stories/editions/ingest'){await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(ingestResponse())});return}if(method==='GET'&&path==='/api/v1/admin/stories/five-friends'){await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(storyDetail())});return}await route.fulfill({status:404,contentType:'application/json',body:JSON.stringify({error:{code:'not_found'}})})});await page.goto('/admin/stories/ingest');await page.locator('#edition-bundle-files').setInputFiles(editionFiles());await expect(page.getByLabel('Title')).toHaveValue('Five Friends');await expect(page.getByLabel('Slug')).toHaveValue('five-friends');await expect(page.getByText('classic.md')).toBeVisible();await expect(page.getByText('little-listeners.md')).toBeVisible();await page.getByRole('button',{name:'Ingest five drafts',exact:true}).first().click();await expect(page).toHaveURL(/\/admin\/stories\/five-friends\?ingested=1&created=5&reused=0/);await expect(page.getByText('Five reading editions ingested as drafts — 5 created, 0 reused. Nothing was published.')).toBeVisible();const ingest=requests.find((item)=>item.method==='POST'&&item.path==='/api/v1/admin/stories/editions/ingest');expect(ingest).toBeTruthy();const body=ingest!.body as {editions:Array<{editionKey:string;markdown:string}>};expect(body.editions.map((item)=>item.editionKey)).toEqual(keys);expect(requests.some((item)=>item.path.includes('/publish')||item.path.includes('/unpublish')||item.path.startsWith('/api/v1/reader/'))).toBe(false)})

test('incomplete file selection never reaches the ingest endpoint',async({page,auth})=>{let ingestCalls=0;await page.route('**/api/v1/admin/**',async(route:Route)=>{auth.assertApplicationRequest(route);if(route.request().method()==='POST'&&new URL(route.request().url()).pathname==='/api/v1/admin/stories/editions/ingest')ingestCalls+=1;await route.fulfill({status:404,contentType:'application/json',body:JSON.stringify({error:{code:'not_found'}})})});await page.goto('/admin/stories/ingest');await page.locator('#edition-bundle-files').setInputFiles(editionFiles(4));await expect(page.getByText(/Choose exactly these five files/)).toBeVisible();await expect(page.getByRole('button',{name:'Ingest five drafts',exact:true}).first()).toBeDisabled();expect(ingestCalls).toBe(0)})
